<?php
session_start();
include_once 'processing.php';
include_once 'config.php';
$db=new DB();
$circle1=new  Circle($db);
$circle1->createCircle();
//$circle1->setCentreX($_POST['name_center_x']+0);
	//$circle1-> setCentreY($_POST['name_center_y']+0);
	//$circle1->setWidth($_POST['width']+0);
	//$circle1->setHeight($_POST['height']+0);
//	$circle1->setStartDegree($_POST['start_circle_degree']+0);
//	$circle1->setEndDegree($_POST['end_circle_degree']+0);
	//imagearc($img,$circle->getCentreX(),$circle->getCentreY(),$circle1->getWidth(),$circle1->getHeight(),$circle1->getStartDegree(),$circle1->getEndDegree(),$white);
	$img = imagecreatetruecolor(300,300);
	$im1 = imagecreatefromjpeg('foto/3.jpg');
	$_SESSION['setCentreX'] =$circle1->getCentreX();
	$rectangle=new Rectangle($db);
$rectangle->createRectangle();
//$rectangle->getTopRightX();
//imagerectangle($img,80,60,240,180,$white);
//$image='foto/2.jpg';
$figure=new Figure($db);
$figure->color();
$path=$figure->setPatch($_SESSION['pach']);
$figure->setImage($_SESSION['photo']);
$figure->setFormatImg($figure->getPatch().$figure->getImage());
echo $figure->getFormatPicture();
echo $figure->getPatch().$figure->getImage();
echo '<br>';
//$figure->setImage($image);
echo $figure->getImage();
$b=$figure->getImage();
$figure->setFormatImg($b);
$figure-> getFormatPicture();
echo $figure-> getFormatImg();
echo $figure-> getFormatPicture();
$path=$figure->setPatch('image/2.jpg');
echo $figure->getPatch().$figure->getImage();
echo '<br>';
print_r ($_SESSION['pach']);
echo '<br>';
print_r ($_SESSION['photo']);
echo '<br>';
echo $figure->getFigure();
imagerectangle($img,$rectangle->getTopRightX(),$rectangle->getTopRightY(),$rectangle->getBottomLeftX(),$rectangle->getBottomLeftY(),$white);


//$_SESSION['figure']="ghg";
echo $rectangle->getTopRightX();
echo $rectangle->getTopRightY();
echo $rectangle->getBottomLeftX();
echo $rectangle->getBottomLeftY();
echo  $_SESSION['figure'];
echo $_SESSION['photo'];
print_r ($_SESSION['pach']);
echo $_SESSION['name_photo'];
echo  $_SESSION['name'];
//print_r($_SESSION['figure']);
?>